[tool.ruff] 
line-length = 120
indent-width = 4
target-version = "py311"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations", 
]
[tool.ruff.lint]
fixable = ["ALL"]
select = ["E", "F", "W", "I", "ERA"]
ignore = [
    "C901",
    "W191",
    "D401",
    "B904",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
    "F403",
    "E402",
]
"conftest.py" = ["F811", "F401"]
"manage.py" = ["E402"]
"tests/*" = [
    "PT019",
    "SIM117",
    "F841",
]
[tool.ruff.lint.isort]
known-first-party = ["app", "config"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "double"
multiline-quotes = "single"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--reuse-db"
filterwarnings = ["ignore::DeprecationWarning"]
