name: Interview CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-slim

    services:
      db:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_DB: appdb
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: dbpassword
        options: >- 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres-service

      cache:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name redis-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Prepare system
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            make \
            gcc \
            git \
            tree \
            libpq-dev \
            gdal-bin libgdal-dev \
            libproj-dev libgeos-dev binutils \
            postgresql-client \
            && apt-get clean \
            && rm -rf /var/lib/apt/lists/*
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          make init

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test

      - name: Run interview tests
        if: github.event_name == 'pull_request'
        run: make interview
